---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: egw
  name: egw-web-service
  namespace: acnodal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: egw
    component: web-service
  name: web-service
  namespace: acnodal
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: egw
      component: web-service
  template:
    metadata:
      labels:
        app: egw
        component: web-service
    spec:
      imagePullSecrets:
      - name: gitlab
      containers:
      - args:
        image: registry.gitlab.com/acnodal/egw/controller:latest
        imagePullPolicy: Always
        name: web-service
        ports:
        - containerPort: 8080
          name: http
          hostPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      serviceAccountName: egw-web-service
      terminationGracePeriodSeconds: 0
---
kind: Service
apiVersion: v1
metadata:
  name: web-service
  namespace: acnodal
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
  selector:
    app: egw
    component: web-service
