---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: egw
  name: xds-operator
  namespace: acnodal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: egw
    component: xds-operator
  name: xds-operator
  namespace: acnodal
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: egw
      component: xds-operator
  template:
    metadata:
      labels:
        app: egw
        component: xds-operator
    spec:
      imagePullSecrets:
      - name: gitlab
      containers:
      - args:
        image: registry.gitlab.com/acnodal/xds-operator/xds-operator:latest
        imagePullPolicy: Always
        name: xds-operator
        ports:
        - containerPort: 8080
          name: http
          hostPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: true
      serviceAccountName: xds-operator
      terminationGracePeriodSeconds: 0
---
kind: Service
apiVersion: v1
metadata:
  name: xds-operator
  namespace: acnodal
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
  selector:
    app: egw
    component: xds-operator
